[theme]
primaryColor = "#5C7AFF"            # A soft primary color
backgroundColor = "#FFFFFF"         # Light background color, almost white
secondaryBackgroundColor = "#E0E0E0" # Slightly darker than the primary background for contrast
textColor = "#333333"               # Dark text color for contrast against light background
font = "sans serif"
